services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: project_gutenberg
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kochumol
    networks:
      - backend

  gutenburg-web:
    build: .
    command: gunicorn gberg.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - ./static:/app/static
    ports:
      - "8000:8000"  # Map Gunicorn's internal port to a host port for debugging
    networks:
      - backend

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/app/static
    ports:
      - "80:80"  # Map Nginx's port 80 to the host
    depends_on:
      - gutenburg-web
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
